networks:
  postgres-network:
    driver: bridge

services:
  postgres:
    container_name: postgres-Student
    image: postgres
    environment:
      POSTGRES_USER: boss
      POSTGRES_PASSWORD: root
#      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4-Student
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"         # if need you can change the port number like this  "5051:80"
    networks:
      - postgres-network
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data: